$background = rgba(12140eff)
$error = rgba(ffb4abff)
$error_container = rgba(93000aff)
$inverse_on_surface = rgba(2f312aff)
$inverse_primary = rgba(4e6629ff)
$inverse_surface = rgba(e3e3d8ff)
$on_background = rgba(e3e3d8ff)
$on_error = rgba(690005ff)
$on_error_container = rgba(ffdad6ff)
$on_primary = rgba(223600ff)
$on_primary_container = rgba(d0eda1ff)
$on_primary_fixed = rgba(121f00ff)
$on_primary_fixed_variant = rgba(374d13ff)
$on_secondary = rgba(2b331dff)
$on_secondary_container = rgba(dde7c6ff)
$on_secondary_fixed = rgba(161e0aff)
$on_secondary_fixed_variant = rgba(414a32ff)
$on_surface = rgba(e3e3d8ff)
$on_surface_variant = rgba(c5c8b9ff)
$on_tertiary = rgba(003733ff)
$on_tertiary_container = rgba(bcece6ff)
$on_tertiary_fixed = rgba(00201eff)
$on_tertiary_fixed_variant = rgba(1f4e4aff)
$outline = rgba(8f9285ff)
$outline_variant = rgba(45483dff)
$primary = rgba(b4d087ff)
$primary_container = rgba(374d13ff)
$primary_fixed = rgba(d0eda1ff)
$primary_fixed_dim = rgba(b4d087ff)
$scrim = rgba(000000ff)
$secondary = rgba(c1caacff)
$secondary_container = rgba(414a32ff)
$secondary_fixed = rgba(dde7c6ff)
$secondary_fixed_dim = rgba(c1caacff)
$shadow = rgba(000000ff)
$source_color = rgba(2b3022ff)
$surface = rgba(12140eff)
$surface_bright = rgba(383a32ff)
$surface_container = rgba(1e2019ff)
$surface_container_high = rgba(292b23ff)
$surface_container_highest = rgba(33362eff)
$surface_container_low = rgba(1a1c16ff)
$surface_container_lowest = rgba(0d0f09ff)
$surface_dim = rgba(12140eff)
$surface_tint = rgba(b4d087ff)
$surface_variant = rgba(45483dff)
$tertiary = rgba(a0d0caff)
$tertiary_container = rgba(1f4e4aff)
$tertiary_fixed = rgba(bcece6ff)
$tertiary_fixed_dim = rgba(a0d0caff)
