$background = rgba(19120cff)
$error = rgba(ffb4abff)
$error_container = rgba(93000aff)
$inverse_on_surface = rgba(372f28ff)
$inverse_primary = rgba(865219ff)
$inverse_surface = rgba(efe0d5ff)
$on_background = rgba(efe0d5ff)
$on_error = rgba(690005ff)
$on_error_container = rgba(ffdad6ff)
$on_primary = rgba(4a2800ff)
$on_primary_container = rgba(ffdcbfff)
$on_primary_fixed = rgba(2d1600ff)
$on_primary_fixed_variant = rgba(6a3b01ff)
$on_secondary = rgba(412c18ff)
$on_secondary_container = rgba(ffdcbfff)
$on_secondary_fixed = rgba(291806ff)
$on_secondary_fixed_variant = rgba(59422dff)
$on_surface = rgba(efe0d5ff)
$on_surface_variant = rgba(d5c3b6ff)
$on_tertiary = rgba(2b340fff)
$on_tertiary_container = rgba(dde8b3ff)
$on_tertiary_fixed = rgba(171e00ff)
$on_tertiary_fixed_variant = rgba(414b24ff)
$outline = rgba(9e8e81ff)
$outline_variant = rgba(51443aff)
$primary = rgba(fdb876ff)
$primary_container = rgba(6a3b01ff)
$primary_fixed = rgba(ffdcbfff)
$primary_fixed_dim = rgba(fdb876ff)
$scrim = rgba(000000ff)
$secondary = rgba(e2c0a4ff)
$secondary_container = rgba(59422dff)
$secondary_fixed = rgba(ffdcbfff)
$secondary_fixed_dim = rgba(e2c0a4ff)
$shadow = rgba(000000ff)
$source_color = rgba(ac7339ff)
$surface = rgba(19120cff)
$surface_bright = rgba(403830ff)
$surface_container = rgba(261e18ff)
$surface_container_high = rgba(312822ff)
$surface_container_highest = rgba(3c332cff)
$surface_container_low = rgba(211a14ff)
$surface_container_lowest = rgba(130d07ff)
$surface_dim = rgba(19120cff)
$surface_tint = rgba(fdb876ff)
$surface_variant = rgba(51443aff)
$tertiary = rgba(c1cc99ff)
$tertiary_container = rgba(414b24ff)
$tertiary_fixed = rgba(dde8b3ff)
$tertiary_fixed_dim = rgba(c1cc99ff)
