#  █████╗ ██╗   ██╗████████╗ ██████╗ ███████╗████████╗ █████╗ ██████╗ ████████╗
# ██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗██╔════╝╚══██╔══╝██╔══██╗██╔══██╗╚══██╔══╝
# ███████║██║   ██║   ██║   ██║   ██║███████╗   ██║   ███████║██████╔╝   ██║
# ██╔══██║██║   ██║   ██║   ██║   ██║╚════██║   ██║   ██╔══██║██╔══██╗   ██║
# ██║  ██║╚██████╔╝   ██║   ╚██████╔╝███████║   ██║   ██║  ██║██║  ██║   ██║
# ╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝ ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝
#------------------------------------------------------------------------------

exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start hyprpolkitagent
exec-once = gnome-keyring-daemon --start --components=secrets,ssh

exec-once = bash -lc '~/.config/hypr/scripts/wallpaper.sh "$(readlink -f ~/.cache/current-wallpaper 2>/dev/null)" 2>/dev/null || ~/.config/hypr/scripts/wallpaper.sh'

exec-once = swaync
exec-once = swayosd-server
exec-once = hypridle

exec-once = bash -c 'until hyprctl monitors >/dev/null 2>&1; do sleep 0.1; done; exec /home/oxdfa/.local/bin/hyprshell run'

exec-once = eww daemon
exec-once = ~/.config/eww/panel/scripts/notif-listener.py
exec-once = bash -lc 'nm-online -q --timeout=20 2>/dev/null; waybar'
